# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: goreleaser_ex
before:
  hooks:
    # You may remove this if you don't use go modules.
    #- go mod tidy
    # you may remove this if you don't need go generate
    #- go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - binaries:
    - main1
  - image_templates:
    - "ghcr.io/slmingol/{{ .ProjectName }}:{{ .Tag }}"
    - "ghcr.io/slmingol/{{ .ProjectName }}:v{{ .Major }}"
    - "ghcr.io/slmingol/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/slmingol/{{ .ProjectName }}:latest"
