# REF: https://github.com/goreleaser/example/blob/master/.goreleaser.yaml

project_name: gorelease_ex
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - image_templates: 
    - "ghcr.io/slmingol/gorelease_ex:{{ .Tag }}"
      #- "slmingol/gorelease_ex:{{ .Tag }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url={{ .GitURL }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--platform=linux/amd64"

#brews:
#  -
#    # Name template of the recipe
#    # Default to project name
#    name: myproject
#
#    # IDs of the archives to use.
#    # Defaults to all.
#    #ids:
#    #- foo
#    #- bar
#
#    # GOARM to specify which 32-bit arm version to use if there are multiple versions
#    # from the build section. Brew formulas support atm only one 32-bit version.
#    # Default is 6 for all artifacts or each id if there a multiple versions.
#    #goarm: 6
#
#    # NOTE: make sure the url_template, the token and given repo (github or gitlab) owner and name are from the
#    # same kind. We will probably unify this in the next major version like it is done with scoop.
#
#    # GitHub/GitLab repository to push the formula to
#    # Gitea is not supported yet, but the support coming
#    tap:
#      owner: slmingol
#      name: homebrew-tap
#      # Optionally a token can be provided, if it differs from the token provided to GoReleaser
#      token: "{{ .Env.GO_RELEASER_HOMEBREW_TOKEN }}"
