# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myproject < Formula
  desc ""
  homepage ""
  version "0.0.45"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/slmingol/gorelease_ex/releases/download/0.0.45/gorelease_ex_0.0.45_Darwin_x86_64.tar.gz"
    sha256 "5259f5fcac9bb8c51cb22c6b2c04b351e51ae6a6638fb12eb4f1711546251329"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/slmingol/gorelease_ex/releases/download/0.0.45/gorelease_ex_0.0.45_Linux_x86_64.tar.gz"
    sha256 "c6acf745197b9b5054385b83659d2c120996e877c1f975072ee21f956f006f5c"
  end

  def install
    bin.install "gorelease_ex"
  end
end
