name: Clean up old package & artifact versions

#---------------------------------------------------------------------------

on:
  push:
    branches:
      - main

  schedule:
    - cron: '5 */6 * * *'

  workflow_dispatch:

#---------------------------------------------------------------------------

jobs:
  package-cleanup:
    runs-on: ubuntu-latest
    steps:
#       - name: Clean up old versions (gpr-janitor)
#         id: clean-up-old-package-versions__gpr-janitor
#         uses: stripethree/gpr-janitor@v2
#         with:
#           dry-run: false
#           keep-versions: 3
#           min-age-days: 1
#           # packages-to-fetch: 1 - (default)
#           versions-to-fetch: 10
#         env:
#           GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}

      - name: Clean up old versions (delete-older-releases)
        id: clean-up-old-package-versions__delete-older-releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: ${{ github.repository_owner }}/gorelease_ex
          keep_latest: 3
          delete_tags: true
          delete_tag_pattern: 0.
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}

#---------------------------------------------------------------------------

##   cleanup_dockerhub_tags:
##     runs-on: ubuntu-latest
##     steps:
##       - name: Delete old dockerhub image tags
##         id: delete_old_tags
##         uses: m3ntorship/action-dockerhub-cleanup@1.2
##         with:
##           token: ${{ secrets.GO_RELEASER_DOCKERHUB_TOKEN }}
##           user: ${{ github.repository_owner }} # same on both GH + dockerhub
##           repos: '["gorelease_ex"]'
##           keep-last: 3 
##            #substrings: '["0.0."]'
##            #force-full-cleanup: true

#---------------------------------------------------------------------------
