name: Clean up old package & artifact versions

#---------------------------------------------------------------------------

on:
  push:
    branches:
      - main

  schedule:
    - cron: '5 */6 * * *'

  workflow_dispatch:

#---------------------------------------------------------------------------

jobs:
  package-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up old versions
        id: clean-up-old-package-versions
        uses: stripethree/gpr-janitor@v2
        with:
          dry-run: false
          keep-versions: 3
          min-age-days: 1
          # packages-to-fetch: 1 - (default)
          versions-to-fetch: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}

#---------------------------------------------------------------------------

  cleanup_dockerhub_tags:
    runs-on: ubuntu-latest
    steps:
      - id: delete_old_tags
        name: Delete old dockerhub image tags
        uses: m3ntorship/action-dockerhub-cleanup@1.2
        with:
          token: ${{ secrets.GO_RELEASER_DOCKERHUB_TOKEN }}
          user: ${{ github.repository_owner }}
          repos: '["gorelease_ex"]'
          keep-last: 3 
          force-full-cleanup: true

#---------------------------------------------------------------------------
