name: Clean up old package & artifact versions

#---------------------------------------------------------------------------

on:
  push:
    branches:
      - main
  schedule:
    - cron: '5 */6 * * *'

#---------------------------------------------------------------------------

jobs:
  package-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up old versions
        id: clean-up-old-package-versions
        uses: stripethree/gpr-janitor@v2
        with:
          dry-run: false
          keep-versions: 3
          min-age-days: 1
          # packages-to-fetch: 1 - (default)
          versions-to-fetch: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}

#---------------------------------------------------------------------------
