name: Clean up old package & artifact versions

#---------------------------------------------------------------------------

on:
  push:
    branches:
      - main

  schedule:
    - cron: '5 */6 * * *'

  workflow_dispatch:

#---------------------------------------------------------------------------

jobs:
  package-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up old versions
        id: clean-up-old-package-versions
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: ${{ github.repository_owner }}/gorelease_ex
          keep_latest: 2
          delete_tags: true
          delete_tag_pattern: 0.
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}

#---------------------------------------------------------------------------

  cleanup_dockerhub_tags:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old dockerhub image tags
        id: delete_old_tags
        uses: m3ntorship/action-dockerhub-cleanup@1.2
        with:
          token: ${{ secrets.GO_RELEASER_DOCKERHUB_TOKEN }}
          user: 'slmingol'
          keep-last: 3 
          force-full-cleanup: true

           #substrings: '["0.0."]'
            #repos: '["gorelease_ex"]'
            #user: 'slmingol'   #${{ github.repository_owner }} # same on both GH + dockerhub

#---------------------------------------------------------------------------
